### ISSUE TITLE
Strict dependency on androidx 2.0.0

### ISSUE THREAD

**Issue by Maragues** [jraska/livedata-testing#47]
I tried to upgrade to androidx stable version 2.1.0, but gradle complains that there's a strict dependency on 2.0.0.

My feeling is that this is coming from your library, but I'm not 100% sure. Please close the ticket if you don't think that's the case.

Thanks!

**Comment by jraska** [comment]
Hi @Maragues , thanks for reaching out and using the library! :)

I believe the dependency is not strict.

You could run `./gradlew dependencies` or `./gradlew :{module name}:dependencies` to see where it is coming from. Please let me know the result.

Thanks

Josef

**Comment by Maragues** [comment]
Thanks, closing this for now.

And thanks a lot for the library, sorry I was blunt at first!

**Comment by Maragues** [comment]
Apparently you don't set it as a strict dependency, so the issue is somewhere else.

I had to jump to other stuff, but I think it's unrelated to your code
