### ISSUE TITLE
Test results uploading on Circle CI not finding the file

### ISSUE THREAD

**Issue by lordcodes** [jraska/livedata-testing#7]
Just incase you hadn't noticed.
The step in CI to upload test results (to attach to the build results) is failing to find the test results files, so they are silently failing.

**Comment by jraska** [comment]
Oh I didn't. Thank you!

**Comment by jraska** [comment]
Fixed, thanks again for noticing :) I was renaming modules due to bintray upload and this was side effect :D

**Comment by lordcodes** [comment]
Ahh okay. No worries, was just looking at the Circle CI setup and noticed!
😆
