### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by jraska** [jraska/livedata-testing#78]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Edit: **UPDATE 4/27/2021:** We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

**Comment by lordcodes** [comment]
https://blog.autsoft.hu/publishing-an-android-library-to-mavencentral-in-2019/

Has some of the details of actually registering with Maven Central, then there are more up-to-date guides for the actual Gradle configuration publishing part.

**Comment by jraska** [comment]
Thanks for that @lordcodes  :) fortunately the whole things shifted timelines to a bit later, but I have to do it at some point - it just feels so painful :D

**Comment by lordcodes** [comment]
Yeah I think many people will want to remove jcenter sooner from their projects, but can set it to only use jcenter for whichever dependencies need it, to avoid accidentally adding more jcenter only stuff to the project.

**Comment by lordcodes** [comment]
I will be attempting to do this soon for my 'turtle' project as that is currently Bintray only, will let you know if I hit any issues.

**Comment by jraska** [comment]
Cool, thanks :) Just seeing "create a Jira ticket" in instructions gives me the shivers

**Comment by jraska** [comment]
https://developer.android.com/studio/build/maven-publish-plugin

Maintenance on publishing needed.

**Comment by jraska** [comment]
https://issues.sonatype.org/browse/OSSRH-69306

**Comment by jraska** [comment]
LiveData Testing [is now on Maven Central](https://repo1.maven.org/maven2/com/jraska/livedata/) starting with [the version 1.2.0](https://github.com/jraska/livedata-testing/releases/tag/1.2.0).

Kotlin:
```groovy
testImplementation 'com.jraska.livedata:testing-ktx:1.2.0'
```
Java:
```groovy
testImplementation 'com.jraska.livedata:testing:1.2.0'
